// =============================================
// DATA
// =============================================

export const DEFAULT_TASKS = {
  lunes: [
    { id: 'l1', cat: 'cocina', icon: '🍲', text: 'Meal prep principal: viandas para llevar (martes a jueves) y comidas de casa hasta el miércoles' },
    { id: 'l2', cat: 'cocina', icon: '📋', text: 'Revisar el menú e ingredientes necesarios para saber qué y cuánto cocinar' },
    { id: 'l3', cat: 'limpieza', icon: '🚿', text: 'Baños' },
    { id: 'l4', cat: 'limpieza', icon: '🛋️', text: 'Living y comedor — limpieza general' },
    { id: 'l5', cat: 'limpieza', icon: '🍳', text: 'Cocina — limpieza general' },
    { id: 'l6', cat: 'limpieza', icon: '🛏️', text: 'Hacer camas' },
    { id: 'l7', cat: 'ropa', icon: '👕', text: 'Poner lavarropas con la ropa del fin de semana (mientras cocina)' },
    { id: 'l8', cat: 'ropa', icon: '💨', text: 'Pasar a tender al finalizar' },
    { id: 'l9', cat: 'ropa', icon: '🧺', text: 'Planchar y guardar lo que se lavó el viernes' },
  ],
  miercoles: [
    { id: 'm1', cat: 'cocina', icon: '🥘', text: 'Refuerzo puntual: reponer lo que se agotó del meal prep del lunes' },
    { id: 'm2', cat: 'cocina', icon: '🥗', text: 'Algo fresco si se necesita (ensalada, guarnición, etc.)' },
    { id: 'm3', cat: 'limpieza', icon: '🚿', text: 'Limpieza profunda: baños y cocina' },
    { id: 'm4', cat: 'limpieza', icon: '🏠', text: 'Limpieza general del resto de la casa' },
    { id: 'm5', cat: 'limpieza', icon: '🛏️', text: 'Hacer camas' },
    { id: 'm6', cat: 'ropa', icon: '🧺', text: 'Planchar y guardar la ropa lavada el lunes' },
    { id: 'm7', cat: 'ropa', icon: '👕', text: 'Nueva tanda al lavarropas' },
  ],
  viernes: [
    { id: 'v1', cat: 'cocina', icon: '🍽️', text: 'Meal prep para el fin de semana' },
    { id: 'v2', cat: 'limpieza', icon: '🚿', text: 'Baños' },
    { id: 'v3', cat: 'limpieza', icon: '🛋️', text: 'Living y comedor — limpieza general' },
    { id: 'v4', cat: 'limpieza', icon: '🍳', text: 'Cocina — limpieza general' },
    { id: 'v5', cat: 'limpieza', icon: '🛏️', text: 'Hacer camas' },
    { id: 'v6', cat: 'ropa', icon: '🧺', text: 'Planchar y guardar la ropa del miércoles' },
    { id: 'v7', cat: 'ropa', icon: '👕', text: 'Lavar lo acumulado de la semana' },
  ]
};

export const CATEGORIES = {
  cocina: { label: 'Cocina', icon: '🍳' },
  limpieza: { label: 'Limpieza', icon: '🧹' },
  ropa: { label: 'Ropa', icon: '👕' },
};

export function getCurrentSeason() {
  const m = new Date().getMonth() + 1;
  if (m >= 12 || m <= 2) return 'verano';
  if (m >= 3 && m <= 5) return 'otono';
  if (m >= 6 && m <= 8) return 'invierno';
  return 'primavera';
}

export const PRELOADED_RECIPES = [
  { id: 'r1', emoji: '🥗', name: 'Ensalada de quinoa con vegetales', time: 20, tags: ['rapido', 'singluten', 'calor'], ingredients: [{ name: 'Quinoa', amount: '200 g' }, { name: 'Pepino', amount: '1 unidad' }, { name: 'Tomates cherry', amount: '150 g' }, { name: 'Morrón rojo', amount: '1 unidad' }, { name: 'Limón', amount: '1 unidad' }, { name: 'Aceite de oliva', amount: '3 cdas' }, { name: 'Sal y perejil', amount: 'A gusto' }], steps: ['Cocinar quinoa con 2 partes de agua por 1 de quinoa, 15 min. Dejar enfriar.', 'Picar pepino, cherry y morrón en cubos chicos.', 'Mezclar todo con aceite, jugo de limón, sal y perejil.', 'Guardar en heladera hasta servir.'], conservation: 'Hasta 3 días en heladera. No congela.' },
  { id: 'r2', emoji: '🐟', name: 'Medallones de merluza con ensalada', time: 25, tags: ['rapido', 'singluten', 'calor', 'finde'], ingredients: [{ name: 'Merluza en postas', amount: '1 kg' }, { name: 'Ajo', amount: '3 dientes' }, { name: 'Limón', amount: '2 unidades' }, { name: 'Aceite de oliva', amount: '3 cdas' }, { name: 'Lechuga', amount: '1 planta' }, { name: 'Tomate', amount: '2 unidades' }, { name: 'Sal y pimienta', amount: 'A gusto' }], steps: ['Marinar el pescado con limón, ajo, sal y pimienta 15 min.', 'Cocinar en sartén con aceite 4 min por lado.', 'Armar ensalada con lechuga y tomate en rodajas.', 'Servir el pescado sobre la ensalada con un chorro de limón.'], conservation: 'Consumir el día. El pescado cocido dura 1 día en heladera.' },
  { id: 'r3', emoji: '🥚', name: 'Tortilla de verduras', time: 30, tags: ['rapido', 'singluten', 'fresco'], ingredients: [{ name: 'Huevos', amount: '6 unidades' }, { name: 'Zucchini', amount: '1 unidad' }, { name: 'Espinaca', amount: '100 g' }, { name: 'Queso rallado sin TACC', amount: '50 g' }, { name: 'Aceite de oliva', amount: '2 cdas' }, { name: 'Sal, pimienta, nuez moscada', amount: 'A gusto' }], steps: ['Saltear zucchini en rodajas y espinaca hasta ablandar.', 'Batir huevos con sal, pimienta y nuez moscada.', 'Mezclar huevos con verduras y queso.', 'Cocinar en sartén aceitada tapado a fuego bajo 10 min.', 'Dar vuelta con cuidado y cocinar 5 min más.'], conservation: 'Hasta 3 días en heladera. Se puede comer fría. No congela bien.' },
  { id: 'r4', emoji: '🥩', name: 'Carne a la plancha con chimichurri', time: 20, tags: ['rapido', 'singluten', 'calor', 'finde'], ingredients: [{ name: 'Bife de chorizo o cuadril', amount: '1 kg' }, { name: 'Ajo', amount: '4 dientes' }, { name: 'Perejil fresco', amount: '1 atado' }, { name: 'Orégano', amount: '1 cdita' }, { name: 'Vinagre de manzana', amount: '2 cdas' }, { name: 'Aceite de oliva', amount: '4 cdas' }, { name: 'Sal, ají molido', amount: 'A gusto' }], steps: ['Mezclar ajo picado, perejil, orégano, vinagre, aceite y ají. Dejar reposar.', 'Calentar la plancha o parrilla al máximo.', 'Salar la carne al momento. Cocinar 3-4 min por lado según grosor.', 'Servir con chimichurri por encima.'], conservation: 'Consumir el día o hasta 2 días en heladera. El chimichurri dura 1 semana.' },
  { id: 'r5', emoji: '🫙', name: 'Pollo marinado y grillado (meal prep)', time: 40, tags: ['mealprep', 'singluten', 'fresco'], ingredients: [{ name: 'Pechugas de pollo', amount: '1.5 kg' }, { name: 'Limón', amount: '2 unidades' }, { name: 'Ajo', amount: '4 dientes' }, { name: 'Mostaza sin TACC', amount: '2 cdas' }, { name: 'Aceite de oliva', amount: '4 cdas' }, { name: 'Pimentón, sal, pimienta', amount: 'A gusto' }], steps: ['Preparar marinada: mezclar limón, ajo, mostaza, aceite y especias.', 'Cubrir el pollo con la marinada y dejar mínimo 30 min.', 'Cocinar en plancha o sartén caliente 5-6 min por lado.', 'Dejar enfriar y cortar en tiras. Guardar en porciones.'], conservation: 'Hasta 4 días en heladera en recipiente hermético. Congela hasta 2 meses.' },
  { id: 'r6', emoji: '🥑', name: 'Bowl de arroz con pollo y palta', time: 35, tags: ['mealprep', 'singluten', 'calor'], ingredients: [{ name: 'Arroz', amount: '300 g' }, { name: 'Pechuga de pollo', amount: '600 g' }, { name: 'Palta', amount: '2 unidades' }, { name: 'Maíz en lata', amount: '1 lata' }, { name: 'Limón', amount: '1 unidad' }, { name: 'Aceite de oliva', amount: '3 cdas' }, { name: 'Sal, comino, pimentón', amount: 'A gusto' }], steps: ['Cocinar arroz según indicaciones del paquete. Dejar enfriar.', 'Condimentar pollo con comino, pimentón, sal. Cocinar en sartén.', 'Cortar pollo en tiras. Pelar y longuear la palta.', 'Armar bowls con arroz, pollo, palta y maíz. Rociar con limón.'], conservation: 'Guardar arroz y pollo separados. Armar con palta al momento. Dura 3 días.' },
  { id: 'r7', emoji: '🥬', name: 'Tabulé de quinoa', time: 25, tags: ['rapido', 'singluten', 'calor'], ingredients: [{ name: 'Quinoa', amount: '200 g' }, { name: 'Pepino', amount: '2 unidades' }, { name: 'Tomate', amount: '3 unidades' }, { name: 'Cebolla de verdeo', amount: '4 tallos' }, { name: 'Menta fresca', amount: '1/2 atado' }, { name: 'Perejil', amount: '1/2 atado' }, { name: 'Limón', amount: '2 unidades' }, { name: 'Aceite de oliva', amount: '4 cdas' }], steps: ['Cocinar quinoa y dejar enfriar completamente.', 'Picar finamente pepino, tomate, cebolla de verdeo, menta y perejil.', 'Mezclar todo con la quinoa fría.', 'Condimentar con jugo de limón, aceite y sal. Refrigerar.'], conservation: 'Hasta 3 días en heladera. Mejor al día siguiente.' },
  { id: 'r8', emoji: '🍳', name: 'Huevos revueltos con vegetales', time: 15, tags: ['rapido', 'singluten', 'fresco'], ingredients: [{ name: 'Huevos', amount: '8 unidades' }, { name: 'Tomate', amount: '2 unidades' }, { name: 'Cebolla de verdeo', amount: '3 tallos' }, { name: 'Morrón', amount: '1 unidad' }, { name: 'Aceite de oliva', amount: '2 cdas' }, { name: 'Sal y pimienta', amount: 'A gusto' }], steps: ['Saltear morrón y cebolla de verdeo 3 min.', 'Agregar tomate en cubos y cocinar 2 min más.', 'Batir huevos con sal y pimienta. Verter sobre las verduras.', 'Revolver a fuego bajo hasta que cuajen pero queden cremosos.'], conservation: 'Consumir al momento. No apto para prep.' },
  { id: 'r9', emoji: '🍗', name: 'Pollo al horno con papas', time: 70, tags: ['mealprep', 'singluten', 'finde', 'fresco'], ingredients: [{ name: 'Muslos o pechugas de pollo', amount: '1.5 kg' }, { name: 'Papas', amount: '800 g' }, { name: 'Aceite de oliva', amount: '4 cdas' }, { name: 'Ajo', amount: '4 dientes' }, { name: 'Pimentón ahumado', amount: '1 cdita' }, { name: 'Sal y pimienta', amount: 'A gusto' }, { name: 'Romero o tomillo', amount: '1 ramita' }], steps: ['Precalentar el horno a 200°C.', 'Cortar las papas en cubos y condimentar con aceite, sal y pimentón.', 'Condimentar el pollo con ajo picado, aceite, sal, pimienta y hierbas.', 'Disponer todo en una asadera. Hornear 50-60 min hasta dorar.', 'Dejar enfriar antes de guardar en porciones.'], conservation: 'Hasta 4 días en heladera. Congela hasta 2 meses.' },
  { id: 'r10', emoji: '🍖', name: 'Carne a la mostaza al horno', time: 60, tags: ['mealprep', 'singluten', 'finde', 'fresco'], ingredients: [{ name: 'Peceto o lomo', amount: '1 kg' }, { name: 'Mostaza sin TACC', amount: '3 cdas' }, { name: 'Ajo', amount: '3 dientes' }, { name: 'Romero', amount: '2 ramitas' }, { name: 'Aceite de oliva', amount: '2 cdas' }, { name: 'Sal y pimienta', amount: 'A gusto' }], steps: ['Mezclar mostaza con ajo picado, aceite, sal y pimienta.', 'Cubrir toda la carne con la mezcla y dejar marinar 30 min mínimo.', 'Colocar en asadera con ramitas de romero.', 'Hornear a 180°C: 45-50 min para punto rosa, 60 min para bien cocido.', 'Reposar 10 min antes de filetear.'], conservation: 'Hasta 4 días en heladera fileteada. Congela bien.' },
  { id: 'r11', emoji: '🍛', name: 'Curry de pollo', time: 45, tags: ['mealprep', 'singluten', 'finde', 'fresco'], ingredients: [{ name: 'Pechuga de pollo', amount: '1 kg' }, { name: 'Leche de coco', amount: '400 ml' }, { name: 'Cebolla', amount: '1 unidad' }, { name: 'Ajo', amount: '3 dientes' }, { name: 'Jengibre fresco', amount: '1 cm' }, { name: 'Pasta de curry sin TACC', amount: '2 cdas' }, { name: 'Tomate', amount: '2 unidades' }, { name: 'Aceite', amount: '2 cdas' }], steps: ['Saltear cebolla, ajo y jengibre en aceite.', 'Agregar pasta de curry y mezclar 1 min.', 'Incorporar pollo en cubos y sellar.', 'Agregar tomate picado y leche de coco.', 'Cocinar 25 min a fuego medio revolviendo a veces.'], conservation: 'Hasta 4 días en heladera. Congela muy bien.' },
  { id: 'r12', emoji: '🥚', name: 'Frittata de espinaca y champiñones', time: 30, tags: ['rapido', 'singluten', 'fresco'], ingredients: [{ name: 'Huevos', amount: '8 unidades' }, { name: 'Espinaca', amount: '150 g' }, { name: 'Champiñones', amount: '200 g' }, { name: 'Queso cremoso sin TACC', amount: '80 g' }, { name: 'Ajo', amount: '2 dientes' }, { name: 'Aceite de oliva', amount: '2 cdas' }, { name: 'Sal, pimienta, nuez moscada', amount: 'A gusto' }], steps: ['Saltear ajo, champiñones y espinaca. Salpimentar.', 'Batir huevos con sal, pimienta y nuez moscada.', 'Mezclar con las verduras y el queso cremoso en trozos.', 'Cocinar en sartén a fuego bajo tapado 12 min.', 'Gratinar 3 min en horno o grill si se desea.'], conservation: 'Hasta 3 días en heladera. Se puede comer fría.' },
  { id: 'r13', emoji: '🥣', name: 'Sopa crema de zapallo', time: 40, tags: ['mealprep', 'singluten', 'frio'], ingredients: [{ name: 'Zapallo', amount: '800 g' }, { name: 'Papa', amount: '2 unidades' }, { name: 'Cebolla', amount: '1 unidad' }, { name: 'Caldo de verduras sin TACC', amount: '1 litro' }, { name: 'Crema de leche', amount: '100 ml' }, { name: 'Aceite', amount: '2 cdas' }, { name: 'Sal, pimienta, nuez moscada', amount: 'A gusto' }], steps: ['Saltear cebolla en aceite hasta transparentar.', 'Agregar zapallo y papa en cubos. Cubrir con caldo.', 'Cocinar 25 min a fuego medio.', 'Procesar con mixer. Agregar crema y ajustar sal.'], conservation: 'Hasta 5 días en heladera. Congela perfectamente (sin crema).' },
  { id: 'r14', emoji: '🫘', name: 'Lentejas guisadas', time: 50, tags: ['mealprep', 'singluten', 'frio'], ingredients: [{ name: 'Lentejas secas', amount: '400 g' }, { name: 'Cebolla', amount: '1 unidad' }, { name: 'Morrón rojo', amount: '1 unidad' }, { name: 'Zanahoria', amount: '2 unidades' }, { name: 'Tomate', amount: '2 unidades' }, { name: 'Chorizo colorado sin TACC', amount: '1 unidad' }, { name: 'Pimentón, comino, sal', amount: 'A gusto' }], steps: ['Remojar las lentejas 30 min y escurrir.', 'Saltear cebolla, morrón y zanahoria en aceite.', 'Agregar chorizo en rodajas y sellar.', 'Incorporar tomate, especias y lentejas. Cubrir con agua.', 'Cocinar 30-35 min hasta que estén tiernas.'], conservation: 'Hasta 5 días en heladera. Congela perfectamente.' },
  { id: 'r15', emoji: '🥩', name: 'Carne estofada con verduras', time: 90, tags: ['mealprep', 'singluten', 'frio'], ingredients: [{ name: 'Carne de res (osobuco o paleta)', amount: '1.2 kg' }, { name: 'Cebolla', amount: '2 unidades' }, { name: 'Zanahoria', amount: '3 unidades' }, { name: 'Tomates perita', amount: '400 g' }, { name: 'Caldo de res sin TACC', amount: '500 ml' }, { name: 'Aceite', amount: '3 cdas' }, { name: 'Ajo, sal, pimienta, pimentón', amount: 'A gusto' }], steps: ['Sellar la carne en aceite caliente por todos lados.', 'Retirar y saltear cebolla y zanahoria en la misma olla.', 'Agregar tomates, ajo y caldo. Volver a poner la carne.', 'Cocinar tapado a fuego bajo 60-70 min.', 'Desmenuzar con tenedor si se desea. Enfriar antes de guardar.'], conservation: 'Hasta 5 días en heladera. Congela muy bien hasta 3 meses.' },
  { id: 'r16', emoji: '🍲', name: 'Cazuela de pollo con vegetales', time: 60, tags: ['mealprep', 'singluten', 'frio'], ingredients: [{ name: 'Muslos de pollo', amount: '1.2 kg' }, { name: 'Papa', amount: '3 unidades' }, { name: 'Zanahoria', amount: '2 unidades' }, { name: 'Choclo en rodajas', amount: '1 unidad' }, { name: 'Cebolla', amount: '1 unidad' }, { name: 'Caldo de verduras sin TACC', amount: '750 ml' }, { name: 'Ajo, orégano, sal, pimienta', amount: 'A gusto' }], steps: ['Sellar los muslos de pollo en aceite caliente.', 'Saltear cebolla y ajo en la misma olla.', 'Agregar papa, zanahoria y choclo. Cubrir con caldo.', 'Incorporar el pollo. Cocinar 40 min tapado a fuego medio.', 'Ajustar sal y servir con el caldo.'], conservation: 'Hasta 4 días en heladera. Congela bien (sin papa).' },
  { id: 'r17', emoji: '🫕', name: 'Guiso de arroz con carne', time: 55, tags: ['mealprep', 'singluten', 'frio'], ingredients: [{ name: 'Carne picada', amount: '600 g' }, { name: 'Arroz', amount: '250 g' }, { name: 'Tomate perita', amount: '400 g' }, { name: 'Cebolla', amount: '1 unidad' }, { name: 'Morrón', amount: '1 unidad' }, { name: 'Caldo de carne sin TACC', amount: '500 ml' }, { name: 'Pimentón, comino, sal', amount: 'A gusto' }], steps: ['Saltear cebolla y morrón en aceite.', 'Agregar carne picada y dorar bien.', 'Incorporar tomate y especias. Cocinar 5 min.', 'Agregar arroz y caldo. Cocinar 20 min revolviendo.', 'Ajustar sal y consistencia con agua si hace falta.'], conservation: 'Hasta 4 días en heladera. El arroz absorbe líquido al reposar; agregar un poco de agua al calentar.' },
  { id: 'r18', emoji: '🥗', name: 'Ensalada de pollo grillado', time: 30, tags: ['rapido', 'singluten', 'fresco'], ingredients: [{ name: 'Pechuga de pollo', amount: '600 g' }, { name: 'Lechuga', amount: '1 planta' }, { name: 'Tomate', amount: '2 unidades' }, { name: 'Zanahoria rallada', amount: '1 unidad' }, { name: 'Limón', amount: '1 unidad' }, { name: 'Aceite de oliva', amount: '3 cdas' }, { name: 'Sal, pimienta, orégano', amount: 'A gusto' }], steps: ['Condimentar el pollo con limón, sal, pimienta y orégano.', 'Cocinar en plancha 5-6 min por lado.', 'Dejar reposar y cortar en tiras.', 'Armar ensalada y colocar el pollo encima. Rociar con aceite y limón.'], conservation: 'El pollo dura 3 días en heladera. Armar la ensalada al momento.' },
  { id: 'r19', emoji: '🍳', name: 'Medallones de pollo caseros', time: 35, tags: ['mealprep', 'singluten', 'fresco'], ingredients: [{ name: 'Pechuga de pollo molida o picada', amount: '800 g' }, { name: 'Huevo', amount: '2 unidades' }, { name: 'Ajo en polvo', amount: '1 cdita' }, { name: 'Pimentón', amount: '1 cdita' }, { name: 'Harina de arroz sin TACC', amount: '3 cdas' }, { name: 'Sal, pimienta, orégano', amount: 'A gusto' }, { name: 'Aceite', amount: '3 cdas' }], steps: ['Mezclar pollo con huevo, especias y harina de arroz.', 'Formar medallones con las manos húmedas.', 'Cocinar en sartén con aceite 4-5 min por lado.', 'Dejar enfriar sobre papel absorbente.'], conservation: 'Hasta 4 días en heladera. Congela muy bien (hasta 2 meses).' },
  { id: 'r20', emoji: '🥦', name: 'Verduras asadas al horno', time: 40, tags: ['rapido', 'singluten', 'fresco'], ingredients: [{ name: 'Zucchini', amount: '2 unidades' }, { name: 'Morrón rojo y amarillo', amount: '2 unidades' }, { name: 'Berenjena', amount: '1 unidad' }, { name: 'Cebolla', amount: '1 unidad' }, { name: 'Aceite de oliva', amount: '4 cdas' }, { name: 'Ajo en polvo, orégano, sal', amount: 'A gusto' }], steps: ['Cortar todas las verduras en trozos similares.', 'Condimentar con aceite, ajo, orégano y sal.', 'Distribuir en asadera sin superponer.', 'Hornear a 200°C por 30-35 min, dando vuelta a la mitad.'], conservation: 'Hasta 4 días en heladera. Perfectas como guarnición o en ensaladas.' },
];
